apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: kylemunn@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - "fuzzball.me"
      dns01:
        cloudflare:
          email: kylemunn@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token