apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: "authentik.fuzzball.me"
  namespace: authentik
spec:
  endpoints:
  - dnsName: "authentik.fuzzball.me"
    recordTTL: 180
    recordType: CNAME
    targets:
    - "traefik-ingress.fuzzball.me"