apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: 1.13.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 12h
  timeout: 5m
  releaseName: cert-manager
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity